# Generated by Django 2.2.7 on 2020-04-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe',
        ),
    ]
