# Generated by Django 2.2.7 on 2020-04-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodie', '0002_remove_recipe_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe',
            field=models.TextField(blank=True),
        ),
    ]
