# Generated by Django 2.2.7 on 2020-04-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0003_statusmessage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmessage',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
